import { Inter } from "next/font/google";
import "./globals.css";
import GithubProvider from "@/providers/GithubProvider";
import FormDataProvider from "@/providers/FormDataProvider";
import { Toaster } from "@/components/ui/toaster"
import Footer from "../components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} dark`}>
        <GithubProvider>
          <FormDataProvider>
            <Toaster />
            {children}
            <Footer />
          </FormDataProvider>
        </GithubProvider>
      </body>
    </html>
  );
}
